/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.dycn.airportconsumer.faceplate.avro;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum NewFeatureType {
  RGB_FEATURE, INFRARED_FEATURE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"NewFeatureType\",\"namespace\":\"com.oliveapp.libhttpservice.avro\",\"symbols\":[\"RGB_FEATURE\",\"INFRARED_FEATURE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
