/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.dycn.airportconsumer.faceplate.avro;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum NewImageType {
  SCENE_IMAGE, CAPTURED_IMAGE, INFRARED_SCENE_IMAGE, INFRARED_CAPTURED_IMAGE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"NewImageType\",\"namespace\":\"com.oliveapp.libhttpservice.avro\",\"symbols\":[\"SCENE_IMAGE\",\"CAPTURED_IMAGE\",\"INFRARED_SCENE_IMAGE\",\"INFRARED_CAPTURED_IMAGE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
