/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.dycn.airportconsumer.faceplate.avro;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum OperationType {
  ADD, REMOVE, MODIFY  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"OperationType\",\"namespace\":\"com.oliveapp.libhttpservice.avro\",\"symbols\":[\"ADD\",\"REMOVE\",\"MODIFY\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
