spring:
  rabbitmq:
    host: 10.138.25.20 #ip
    port: 5672      #端口
    username: admin #账号
    password: 111111 #密码
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: manual
    virtual-host: /

